"""AI Score 默认评分规则。"""

from __future__ import annotations


DEFAULT_RULES: dict[str, dict[str, object]] = {
    "supplier_score": {
        "base_score": 16,
        "factory_points": 24,
        "powerful_merchant_points": 10,
        "deep_factory_points": 10,
        "trustpass_points": 10,
        "open_years_points": 8,
        "rating_points": 10,
        "repurchase_points": 6,
        "response_points": 6,
        "ships_48h_points": 6,
        "drop_shipping_points": 5,
        "oem_points": 4,
        "logo_custom_points": 3,
        "moq_points": 4,
        "max_good_moq": 10,
    },
    "product_score": {
        "base_score": 15,
        "sales_points": 25,
        "sales_growth_points": 15,
        "favorite_points": 10,
        "review_points": 10,
        "positive_rate_points": 10,
        "stock_points": 10,
        "updated_points": 5,
        "high_sales": 10000,
        "good_sales": 1000,
        "good_positive_rate": 0.95,
    },
    "profit_score": {
        "logistics_cost": 3.0,
        "packaging_cost": 1.0,
        "platform_commission_rate": 0.08,
        "markup_rate": 2.2,
        "target_profit_margin": 0.35,
        "risk_buffer_rate": 0.08,
        "min_markup_rate": 1.6,
        "use_existing_suggested_price": False,
        "non_factory_profit_score_penalty": 0.15,
        "good_profit_margin": 0.35,
        "good_roi": 1.0,
    },
    "price_score": {
        "base_score": 50,
        "free_shipping_points": 15,
        "low_shipping_points": 10,
        "price_stability_points": 15,
        "market_price_factor": 1.15,
    },
    "fulfillment_score": {
        "base_score": 35,
        "ships_48h_points": 20,
        "stock_stable_points": 15,
        "after_sales_points": 10,
        "order_process_points": 10,
        "fast_response_points": 10,
    },
    "recommendation_levels": {
        "S": {"min": 90, "label": "强烈推荐"},
        "A": {"min": 80, "label": "推荐"},
        "B": {"min": 70, "label": "可观察"},
        "C": {"min": 60, "label": "谨慎"},
        "D": {"min": 0, "label": "不推荐"},
    },
    "risk": {
        "low_profit_margin": 0.2,
        "low_roi": 0.5,
        "low_sales": 100,
        "high_moq": 100,
        "low_ai_score": 60,
    },
}
